from . import exam_evaluation
from . import exam_result
from . import exam_seating
from . import exam_timetable
from . import examination
from . import grade_system
from . import hall_ticket
from . import marksheet
from . import revaluation